### ISSUE TITLE
**installing 'cairo-devel' native package... failed**

### ISSUE THREAD

**Issue by slashTPA** [CoRfr/spex-3gpp#6]
Hi there,

while install via

**$ bundle install**

on RHEL 8.2 I run into the issue:

Installing cairo 1.16.4 with native extensions
Gem::Ext::BuildError: ERROR: **Failed to build gem native extension.**

    current directory: /tmp/bundler20200518-80090-11x4alwcairo-1.16.4/gems/cairo-1.16.4/ext/cairo
/usr/bin/ruby -r ./siteconf20200518-80090-gpvo95.rb extconf.rb
checking for GCC... yes
checking for Homebrew... no
checking for cairo version (>= 1.2.0)... no
**installing 'cairo-devel' native package... failed**
Failed to run '/usr/bin/sudo -p \[sudo\]\ password\ for\ \%u\ to\ install\ \<cairo-devel\>:\  dnf install --enablerepo=PowerTools -y cairo-devel'.
*** extconf.rb failed ***

Without going deeper into it - was anyone successful to install on RHEL 8.2 ? There is no such repo like 'PowerTools' available - and that can be seen as well in the log:

---------
$ cat /home/__tpa/.gem/ruby/extensions/x86_64-linux/2.5.0/cairo-1.16.4/mkmf.log
checking for GCC... -------------------- yes

"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic  -m64   -lruby    -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -m64  -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: #ifndef __GNUC__
5: # error
6: |:/ === __GNUC__ undefined === /:|
7: #endif
/* end */

--------------------

checking for Homebrew... -------------------- no

--------------------

have_package: checking for cairo version (>= 1.2.0)... -------------------- no

--------------------

"/usr/bin/sudo -p \[sudo\]\ password\ for\ \%u\ to\ install\ \<cairo-devel\>:\  dnf install --enablerepo=PowerTools -y cairo-devel"
Updating Subscription Management repositories.
**Fehler: Unbekannte Paketquelle: »PowerTools«**
installing 'cairo-devel' native package... failed
Failed to run '/usr/bin/sudo -p \[sudo\]\ password\ for\ \%u\ to\ install\ \<cairo-devel\>:\  dnf install --enablerepo=PowerTools -y cairo-devel'.
--------------------

----------

Any hints?

**Comment by CoRfr** [comment]
It looks like it's trying to do some operations as root using sudo while installing 'cairo-devel' and that fails. I've never tried running it with RHEL, as so far I always used Docker to deploy it and did the development on either Debian or Arch machines.

**Comment by slashTPA** [comment]
well yes, these PowerTools do not exist in RHEL8.2.
Anyway, as well the docker version is not that straight forward on RHEL due to podman not supporting dns resolution between the containers... and what ever in addition, that keeps me still blocking from accessing localhost:3000.

I suggest to close this here for the moment (as I switched to Ubuntu). If time allows I'll lock into the RHEL implementation some when...
